import{ArrowRight,ArrowUpRight,FlaskConical,CheckCheck,Clock3,Terminal,Activity,Cloud,BrainCircuit,Target}from'lucide-react'
import{useAcademy}from'../context/AcademyContext'
import{nextLesson,dueReviews,stages}from'../services/progress'
import{daysLeft,dayDate,planEnd,shortDate}from'../utils/dates'
import{Badge,Meter,Check}from'../components/ui/Common'
export function Dashboard(){const{course,progress}=useAcademy();const next=nextLesson(course,progress);const complete=progress.completed.length;const labs=Object.values(progress.labs).filter(Boolean).length;const due=dueReviews(progress).length;const end=planEnd(progress.settings.start_date,progress.settings.daily_hours);return <>
 <div className="welcome-row"><p>SEU PLANO. SUA EVOLUÇÃO.</p><span><i className="tiny-dot"/> Missão em andamento</span></div>
 <section className="hero"><div className="hero-copy"><Badge tone="lime-badge">TRILHA AIOPS · 30 AULAS</Badge><h1>Da primeira linha<br/>ao próximo <em>nível.</em></h1><p>Seu próximo nível começa na prática. Construa a base, automatize com confiança e aprenda a resolver o que importa.</p><div className="hero-actions"><a className="primary" href={`#/day/${next.day}`}>{complete?'Continuar minha missão':'Começar minha missão'}<ArrowUpRight size={19}/></a><a className="text-button" href="#/tracks">Explorar as trilhas <ArrowRight size={16}/></a></div><div className="hero-foot"><span><Clock3 size={14}/> {progress.settings.daily_hours*60} min por dia</span><span><FlaskConical size={14}/>Prática desde o dia 1</span><span><Target size={14}/>Do zero à autonomia</span></div></div><div className="hero-art" aria-hidden="true"><div className="grid-art"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><svg viewBox="0 0 420 300" className="art-line"><path d="M-20 210h75l25-22 35 38 38-105 40 69 35-20 40-95 30 44 27-63h110"/><path className="art-line-dim" d="M-20 255h95l30-12 55 11 40-42 38 23 39-70 45 35 41-45h70"/></svg><div className="art-tag tag-top"><span/>SISTEMAS OBSERVÁVEIS</div><div className="art-core"><Activity size={34}/><strong>AIOps<span>OPERAÇÕES + INTELIGÊNCIA</span></strong></div><div className="art-tag tag-bottom"><CheckCheck size={14}/>HIPÓTESE → EVIDÊNCIA → AÇÃO</div><div className="art-coordinate">LEARN / BUILD / OPERATE</div></div></section>
 <section className="stats-grid" aria-label="Seu progresso"><div className="stat"><span>JORNADA CONCLUÍDA<CheckCheck size={17}/></span><strong>{String(complete).padStart(2,'0')}<small>/ 30 aulas</small></strong><Meter value={Math.round(complete/30*100)} label="Aulas concluídas"/></div><div className="stat"><span>LABORATÓRIOS RESOLVIDOS<FlaskConical size={17}/></span><strong>{String(labs).padStart(2,'0')}<small>/ {course.labs.length} bancadas</small></strong><p>Aprendizado que vira evidência</p></div><div className="stat"><span>REVISÕES PARA HOJE<Clock3 size={17}/></span><strong>{String(due).padStart(2,'0')}<small>conceitos</small></strong><a href="#/reviews">Fortaleça o que aprendeu <ArrowRight size={14}/></a></div><div className="stat"><span>ATÉ O FIM DO SEU CICLO<Target size={17}/></span><strong>{Math.max(0,daysLeft(end))}<small>dias</small></strong><a href="#/settings">Previsão: {shortDate(end)} · ajustar</a></div></section>
 <div className="dashboard-columns"><section><div className="section-heading"><h2>Sua próxima missão</h2><a href="#/trail">Ver todas as aulas <ArrowUpRight size={16}/></a></div><a className="next-mission panel" href={`#/day/${next.day}`}><div className="mission-top"><Badge>AULA {String(next.day).padStart(2,'0')}</Badge><span>{dayDate(progress.settings.start_date,next.day,progress.settings.daily_hours)} · {next.track}</span></div><h3>{next.title}</h3><p>{next.summary}</p><div className="mission-checks"><span><Check done={false}/>Aprenda o fundamento</span><span><Check done={!!progress.labs[next.lab]}/>Resolva o laboratório</span><span><Check done={(progress.quizzes[next.day]||0)>=80}/>Prove no checkpoint</span></div><div className="mission-bottom"><span><Clock3 size={16}/>{(progress.settings.daily_hours===5?next.minutes:180)/60+'h de conteúdo · divida em sessões'}</span><span className="circle-arrow"><ArrowUpRight size={22}/></span></div></a></section><section><div className="section-heading"><h2>Aprender fazendo</h2><a href="#/labs">Abrir laboratório <ArrowUpRight size={16}/></a></div><div className="lab-shortcuts">{[{id:'ansible',icon:Terminal,title:'Automação com Ansible',sub:'YAML, estado e idempotência',tone:'green'},{id:'dql',icon:Activity,title:'Investigação com DQL',sub:'Dos logs à hipótese certa',tone:'blue'},{id:'events',icon:Cloud,title:'AWS + GCP na prática',sub:'Eventos, duplicatas e falhas',tone:'orange'},{id:'incident',icon:BrainCircuit,title:'Arena de incidentes',sub:'Decida. Mitigue. Verifique.',tone:'purple'}].map(({id,icon:Icon,title,sub,tone})=><a href={'#/lab/'+id} className="lab-shortcut" key={id}><span className={'tile-icon '+tone}><Icon size={20}/></span><span><strong>{title}</strong><small>{sub}</small></span><ArrowUpRight size={17}/></a>)}</div></section></div>
 <section className="journey-section"><div className="section-heading"><h2>Um plano. Cinco etapas.</h2><span className="muted">142h no percurso completo · 90h no essencial</span></div><div className="stage-grid">{stages.map((stage,i)=>{const done=progress.completed.filter(x=>x>=stage.range[0]&&x<=stage.range[1]).length;return <a href={`#/day/${stage.range[0]}`} className="stage-card" key={stage.title}><span className="stage-number">0{i+1}</span><span className="stage-days">AULAS {stage.range[0]}—{stage.range[1]}</span><h3>{stage.title}</h3><p>{stage.subtitle}</p><Meter value={Math.round(done/(stage.range[1]-stage.range[0]+1)*100)} label={stage.title}/></a>})}</div></section>
 <div className="method-note"><span>APRENDER NÃO É MARCAR UMA CAIXA.</span><p>Cada aula pede prática, checkpoint e uma evidência sua. A pontuação acompanha os exercícios; a autonomia aparece quando você consegue explicar e resolver uma variação.</p><a href="#/library">Como usar o curso <ArrowRight size={16}/></a></div>
 </>}
