import {ArrowLeft,BookOpen,FlaskConical} from 'lucide-react'
import {useEffect,useState} from 'react'
import {useUnitLesson} from '../hooks/useUnitLesson'
import {Badge,External,Message,PageTitle} from '../components/ui/Common'
import {Markdown} from '../components/ui/Markdown'
import {useAcademy} from '../context/AcademyContext'
import {completeUnit,saveUnitNote} from '../api/unitProgress'

export function UnitLessonPage({unitId}:{unitId:string}) {
  const {lesson,error,loading,retry}=useUnitLesson(unitId)
  const {progress,refresh}=useAcademy()
  const state=progress.unit_progress[unitId]||{lab_passed:false,completed:false,note:'',review:null}
  const draftKey=`academy-unit-note-${unitId}`
  const [note,setNote]=useState(()=>{try{return localStorage.getItem(draftKey)??state.note}catch{return state.note}})
  const [message,setMessage]=useState('')
  const [saving,setSaving]=useState(false)
  useEffect(()=>{try{setNote(localStorage.getItem(`academy-unit-note-${unitId}`)??state.note)}catch{setNote(state.note)}},[unitId,state.note])
  async function act(action:()=>Promise<unknown>,success:string){setSaving(true);setMessage('');try{await action();try{localStorage.removeItem(draftKey)}catch{}await refresh();setMessage(success)}catch(reason){setMessage((reason as Error).message)}finally{setSaving(false)}}
  if(loading)return <><PageTitle eyebrow="AULA GUIADA" title="Carregando aula" description="Preparando o conteúdo local…"/><p role="status">Carregando aula…</p></>
  if(error||!lesson)return <><PageTitle eyebrow="AULA GUIADA" title="Aula indisponível" description="Não foi possível carregar este conteúdo local."/><Message text={error||'Aula não encontrada.'} error/><button className="primary" onClick={retry}>Tentar novamente</button><a className="back-link" href="#/tracks">Voltar às trilhas</a></>
  function edit(value:string){setNote(value);try{localStorage.setItem(draftKey,value)}catch{setMessage('Não foi possível guardar o rascunho no navegador. Salve a evidência antes de sair.')}}
  return <><a className="back-link" href={`#/tracks/${unitId.split('-')[0]}`}><ArrowLeft size={16}/>Voltar à trilha</a><PageTitle eyebrow={`AULA GUIADA · ${unitId.toUpperCase()}`} title={lesson.title} description={lesson.summary} action={<Badge tone={state.completed?'lime-badge':''}>{state.completed?'Concluída':'Em andamento'}</Badge>}/><div className="notice"><strong>Prática sintética e guiada</strong><p>{lesson.practice?.limitations}</p><p>O resultado correto do lab, sua evidência e a conclusão ficam no seu progresso local e entram no backup. Use somente exemplos locais e não informe dados de trabalho.</p></div><div className="lesson-columns"><section className="lesson-paper"><div className="objectives"><p className="eyebrow">LEIA, PRATIQUE E EXPLIQUE</p><p><BookOpen size={16}/>Conteúdo em português · revisão {lesson.content_version}</p></div><Markdown text={lesson.body}/></section><aside className="lesson-aside"><div className="panel"><FlaskConical size={22}/><p className="eyebrow">PRÁTICA LOCAL</p><h3>{lesson.practice?.title}</h3><p className="muted">{lesson.duration_minutes?.essential} min essenciais · {lesson.duration_minutes?.complete} min com variação</p><a className="primary" href={`#/unit/${unitId}/lab`}>{state.lab_passed?'Revisar lab guiado':'Abrir lab guiado'}</a></div><section className="panel"><p className="eyebrow">EVIDÊNCIA DE APRENDIZADO</p><label htmlFor={`unit-note-${unitId}`}>O que você verificou e por que essa decisão importa?</label><textarea id={`unit-note-${unitId}`} rows={6} maxLength={12000} value={note} onChange={event=>edit(event.target.value)} disabled={saving}/><p className="small muted">{note.trim().length}/80 caracteres mínimos para concluir.</p><button className="secondary" disabled={saving||!note.trim()} onClick={()=>void act(()=>saveUnitNote(unitId,note),'Evidência salva no seu progresso local.')}>Salvar evidência</button><button className="primary" disabled={saving||!state.lab_passed||note.trim().length<80||state.completed} onClick={()=>void act(()=>saveUnitNote(unitId,note).then(()=>completeUnit(unitId)),'Aula concluída. A revisão foi agendada.')}>{state.completed?'Aula concluída':'Concluir aula'}</button>{!state.lab_passed&&<p className="small muted">Resolva o lab guiado para liberar a conclusão.</p>}<Message text={message} error={!!message&&message!=='Evidência salva no seu progresso local.'&&message!=='Aula concluída. A revisão foi agendada.'}/></section><div className="references"><h3>Fontes para aprofundar</h3>{lesson.sources.map(source=><External key={source.url} href={source.url}>{source.title}</External>)}</div></aside></div></>
}
