apiVersion: 1

deleteDatasources:
  - name: Lab Prometheus
    orgId: 1

datasources:
  - name: Lab Prometheus
    uid: lab-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 2s
