export const MAX_SYNC_OPERATIONS=50
export const MAX_SYNC_BYTES=64*1024

const DAYS=new Set(Array.from({length:30},(_,index)=>String(index+1)))
const LABS=new Set(['linux','ansible','ansible-windows','dql','opensearch','slo','events','workflow','anomaly','rag','incident'])
const GUIDED=new Set(['data','security','agents'].flatMap(track=>Array.from({length:track==='agents'?8:6},(_,index)=>`${track}-${String(index+1).padStart(2,'0')}`)))
const HOURS=new Set([0.5,0.75,1,1.5,2,3,5])
const OPERATION_ID=/^[a-z0-9][a-z0-9_-]{7,63}$/i

export function emptySyncState(){return {settings:null,completed:[],notes:{},quizzes:{},labs:{},reviews:{},unit_progress:{}}}
function object(value){return value!==null&&typeof value==='object'&&!Array.isArray(value)}
function validText(value){return typeof value==='string'&&value.length<=12000}
function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const parsed=new Date(`${value}T12:00:00Z`);return !Number.isNaN(parsed.valueOf())&&parsed.toISOString().slice(0,10)===value}
function validSettings(value){return value===null||(object(value)&&validDate(value.start_date)&&HOURS.has(value.daily_hours))}
function validReview(value){return object(value)&&validDate(value.due)&&Number.isInteger(value.interval)&&value.interval>=0&&value.interval<=21&&Number.isFinite(value.last_score)&&value.last_score>=0&&value.last_score<=100}
function state(value){if(!object(value)||!validSettings(value.settings)||!Array.isArray(value.completed)||!object(value.notes)||!object(value.quizzes)||!object(value.labs)||!object(value.reviews)||!object(value.unit_progress))throw new Error('Estado de sincronização inválido.');if(value.completed.some(day=>!Number.isInteger(day)||day<1||day>30)||Object.entries(value.notes).some(([day,text])=>!DAYS.has(day)||!validText(text))||Object.entries(value.quizzes).some(([day,score])=>!DAYS.has(day)||!Number.isFinite(score)||score<0||score>100)||Object.entries(value.labs).some(([id,passed])=>!LABS.has(id)||typeof passed!=='boolean')||Object.entries(value.reviews).some(([day,review])=>!DAYS.has(day)||!validReview(review)))throw new Error('Estado de sincronização inválido.');for(const [unitId,progress] of Object.entries(value.unit_progress)){if(!GUIDED.has(unitId)||!object(progress)||typeof progress.lab_passed!=='boolean'||typeof progress.completed!=='boolean'||!validText(progress.note)||!(progress.review===null||validReview(progress.review)))throw new Error('Estado de sincronização inválido.')}return structuredClone(value)}
function replacement(payload){return !('replace'in payload)||payload.replace===true}
function operation(value){if(!object(value)||!OPERATION_ID.test(value.operation_id)||!object(value.payload))throw new Error('Operação de sincronização inválida.');const p=value.payload;if(value.type==='settings'){if(!validSettings(p.settings)||p.settings===null||!replacement(p))throw new Error('Operação de sincronização inválida.')}else if(value.type==='legacy_complete'){if(!DAYS.has(String(p.day)))throw new Error('Operação de sincronização inválida.')}else if(value.type==='legacy_note'){if(!DAYS.has(String(p.day))||!validText(p.text)||!replacement(p))throw new Error('Operação de sincronização inválida.')}else if(value.type==='legacy_quiz'){if(!DAYS.has(String(p.day))||!Number.isFinite(p.score)||p.score<0||p.score>100)throw new Error('Operação de sincronização inválida.')}else if(value.type==='legacy_lab'){if(!LABS.has(p.lab_id)||p.passed!==true)throw new Error('Operação de sincronização inválida.')}else if(value.type==='legacy_review'){if(!DAYS.has(String(p.day))||!validReview(p.review)||!replacement(p))throw new Error('Operação de sincronização inválida.')}else if(value.type==='guided_progress'){if(!GUIDED.has(p.unit_id)||!['lab_passed','completed','note','review'].some(key=>key in p)||('lab_passed'in p&&typeof p.lab_passed!=='boolean')||('completed'in p&&typeof p.completed!=='boolean')||('note'in p&&!validText(p.note))||('review'in p&&!validReview(p.review))||!replacement(p))throw new Error('Operação de sincronização inválida.')}else throw new Error('Operação de sincronização inválida.');return value}
function conflict(kind,id){return {kind,id}}
export function applySyncOperations(current,operations){const next=state(current);if(!Array.isArray(operations)||operations.length===0||operations.length>MAX_SYNC_OPERATIONS||new TextEncoder().encode(JSON.stringify(operations)).byteLength>MAX_SYNC_BYTES)throw new Error('Lote de sincronização inválido.');const seen=new Set();for(const raw of operations){const item=operation(raw);const p=item.payload;if(seen.has(item.operation_id))throw new Error('Operação de sincronização duplicada.');seen.add(item.operation_id);if(item.type==='settings'){if(next.settings&&JSON.stringify(next.settings)!==JSON.stringify(p.settings)&&p.replace!==true)return {state:next,conflict:conflict('settings','settings')};next.settings=p.settings}else if(item.type==='legacy_complete'){const day=Number(p.day);if(!next.completed.includes(day))next.completed.push(day)}else if(item.type==='legacy_note'){const day=String(p.day);if(next.notes[day]&&next.notes[day]!==p.text&&p.replace!==true)return {state:next,conflict:conflict('legacy_note',day)};next.notes[day]=p.text}else if(item.type==='legacy_quiz'){const day=String(p.day);next.quizzes[day]=Math.max(next.quizzes[day]||0,p.score)}else if(item.type==='legacy_lab'){next.labs[p.lab_id]=true}else if(item.type==='legacy_review'){const day=String(p.day);if(next.reviews[day]&&JSON.stringify(next.reviews[day])!==JSON.stringify(p.review)&&p.replace!==true)return {state:next,conflict:conflict('legacy_review',day)};next.reviews[day]=p.review}else{const id=p.unit_id;const existing=next.unit_progress[id]||{lab_passed:false,completed:false,note:'',review:null};if('note'in p&&existing.note&&existing.note!==p.note&&p.replace!==true)return {state:next,conflict:conflict('guided_note',id)};if('review'in p&&existing.review&&JSON.stringify(existing.review)!==JSON.stringify(p.review)&&p.replace!==true)return {state:next,conflict:conflict('guided_review',id)};next.unit_progress[id]={lab_passed:existing.lab_passed||p.lab_passed===true,completed:existing.completed||p.completed===true,note:'note'in p?p.note:existing.note,review:'review'in p?p.review:existing.review}}}return {state:next,conflict:null}}
