import {deriveCredential} from './credential.mjs'
import {applySyncOperations,emptySyncState} from './sync.mjs'

const MAX_BODY_BYTES=64*1024
const SESSION_DAYS=7
const RECOVERY_CODES=8
const LOGIN_WINDOW_MINUTES=15
const LOGIN_FAILURE_LIMIT=5
const REGISTER_ATTEMPT_LIMIT=3
const RECOVERY_ATTEMPT_LIMIT=5
const HANDLE=/^[a-z0-9][a-z0-9_-]{2,31}$/
const TOKEN_BYTES=32

function response(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}})}
function failure(status,message='Não foi possível concluir esta ação.'){return response({detail:message},status)}
function allowedOrigin(request,env){const origin=request.headers.get('origin');if(!origin)return null;const configured=String(env.ALLOWED_ORIGINS||'').split(',').map(value=>value.trim()).filter(value=>/^https?:\/\/[^/?#]+$/i.test(value));return configured.includes(origin)?origin:null}
function cors(request,env,result){const origin=allowedOrigin(request,env);if(!origin)return result;const headers=new Headers(result.headers);headers.set('access-control-allow-origin',origin);headers.set('access-control-allow-methods','POST, OPTIONS');headers.set('access-control-allow-headers','authorization, content-type');headers.set('vary','Origin');return new Response(result.body,{status:result.status,statusText:result.statusText,headers})}
function preflight(request,env){const origin=allowedOrigin(request,env);if(!origin)return failure(403,'Origem não autorizada.');const headers=request.headers.get('access-control-request-headers')||'';if(request.headers.get('access-control-request-method')!=='POST'||!headers.toLowerCase().split(',').map(value=>value.trim()).every(value=>['authorization','content-type'].includes(value)))return failure(405,'Pré-validação inválida.');return cors(request,env,new Response(null,{status:204}))}
function now(){return new Date().toISOString()}
function futureDays(days){return new Date(Date.now()+days*86400000).toISOString()}
function futureMinutes(minutes){return new Date(Date.now()+minutes*60000).toISOString()}
function base64url(bytes){let text='';for(const byte of bytes)text+=String.fromCharCode(byte);return btoa(text).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function digest(value){return base64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))))}
function randomToken(){const bytes=new Uint8Array(TOKEN_BYTES);crypto.getRandomValues(bytes);return base64url(bytes)}
function recoveryCode(){const values=new Uint8Array(12);crypto.getRandomValues(values);return [...values].map(value=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[value%32]).join('').replace(/(.{3})/g,'$1-').slice(0,-1)}
function handle(value){if(typeof value!=='string')throw new Error('Identificador inválido.');const normalized=value.trim().toLowerCase();if(!HANDLE.test(normalized))throw new Error('Identificador inválido.');return normalized}
function constantTimeEqual(left,right){if(left.length!==right.length)return false;let difference=0;for(let i=0;i<left.length;i++)difference|=left.charCodeAt(i)^right.charCodeAt(i);return difference===0}
async function body(request){if(request.headers.get('content-type')?.split(';')[0]!=='application/json')throw new Error('Envie JSON.');const size=Number(request.headers.get('content-length')||0);if(!Number.isFinite(size)||size>MAX_BODY_BYTES)throw new Error('Entrada excede o limite.');const text=await request.text();if(new TextEncoder().encode(text).byteLength>MAX_BODY_BYTES)throw new Error('Entrada excede o limite.');let value;try{value=JSON.parse(text)}catch{throw new Error('JSON inválido.')}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Entrada inválida.');return value}
async function createSession(db,userId){const token=randomToken();const timestamp=now();await db.prepare('INSERT INTO sessions(session_hash,user_id,created_at,expires_at) VALUES(?,?,?,?)').bind(await digest(token),userId,timestamp,futureDays(SESSION_DAYS)).run();return token}
async function authenticated(request,db){const match=/^Bearer ([A-Za-z0-9_-]{40,60})$/.exec(request.headers.get('authorization')||'');if(!match)throw new Error('Autenticação necessária.');const session=await db.prepare("SELECT user_id FROM sessions WHERE session_hash=? AND revoked_at IS NULL AND expires_at>? LIMIT 1").bind(await digest(match[1]),now()).first();if(!session)throw new Error('Autenticação necessária.');return session.user_id}
function clientAddress(request){const value=request.headers.get('CF-Connecting-IP')||'unknown';return /^[0-9a-f:.]{1,64}$/i.test(value)?value:'unknown'}
function throttleKey(scope,value){return `${scope}:${value}`}
async function throttle(db,key,limit){const timestamp=now();const current=await db.prepare('SELECT failures,window_started_at,blocked_until FROM login_throttles WHERE handle=? LIMIT 1').bind(key).first();if(current?.blocked_until&&current.blocked_until>timestamp)return true;const fresh=!current||Date.parse(current.window_started_at)+LOGIN_WINDOW_MINUTES*60000<Date.now();const failures=fresh?1:Number(current.failures)+1;const blockedUntil=failures>=limit?futureMinutes(LOGIN_WINDOW_MINUTES):null;await db.prepare('INSERT INTO login_throttles(handle,failures,window_started_at,blocked_until) VALUES(?,?,?,?) ON CONFLICT(handle) DO UPDATE SET failures=excluded.failures,window_started_at=excluded.window_started_at,blocked_until=excluded.blocked_until').bind(key,failures,fresh?timestamp:current.window_started_at,blockedUntil).run();return Boolean(blockedUntil)}
async function isBlocked(db,keys){for(const key of keys){const row=await db.prepare('SELECT failures,window_started_at,blocked_until FROM login_throttles WHERE handle=? LIMIT 1').bind(key).first();if(row?.blocked_until&&row.blocked_until>now())return true}return false}
async function rejectIfBlocked(db,keys){return await isBlocked(db,keys)?failure(429,'Muitas tentativas. Tente novamente mais tarde.'):null}
async function register(request,db){const value=await body(request);const userHandle=handle(value.handle);if(typeof value.password!=='string')throw new Error('Credencial inválida.');const limit=await rejectIfBlocked(db,[throttleKey('register-ip',clientAddress(request))]);if(limit)return limit;if(await throttle(db,throttleKey('register-ip',clientAddress(request)),REGISTER_ATTEMPT_LIMIT))return failure(429,'Muitas tentativas. Tente novamente mais tarde.');const exists=await db.prepare('SELECT user_id FROM accounts WHERE handle=? LIMIT 1').bind(userHandle).first();if(exists)return failure(409,'Identificador indisponível.');const userId=crypto.randomUUID();const timestamp=now();const salt=new Uint8Array(16);crypto.getRandomValues(salt);const verifier=await deriveCredential(value.password,salt);const codes=Array.from({length:RECOVERY_CODES},recoveryCode);const statements=[
 db.prepare('INSERT INTO accounts(user_id,handle,created_at) VALUES(?,?,?)').bind(userId,userHandle,timestamp),
 db.prepare('INSERT INTO credential_verifiers(user_id,verifier,updated_at) VALUES(?,?,?)').bind(userId,verifier,timestamp)
];for(const code of codes){const codeSalt=new Uint8Array(16);crypto.getRandomValues(codeSalt);statements.push(db.prepare('INSERT INTO recovery_codes(user_id,code_hash,created_at) VALUES(?,?,?)').bind(userId,await deriveCredential(code,codeSalt),timestamp))}
 await db.batch(statements);const token=await createSession(db,userId);return response({handle:userHandle,session_token:token,recovery_codes:codes})}
async function login(request,db){const value=await body(request);const userHandle=handle(value.handle);if(typeof value.password!=='string')throw new Error('Credencial inválida.');const keys=[throttleKey('login-handle',userHandle),throttleKey('login-ip',clientAddress(request))];const limit=await rejectIfBlocked(db,keys);if(limit)return limit;const record=await db.prepare('SELECT a.user_id,c.verifier FROM accounts a JOIN credential_verifiers c ON c.user_id=a.user_id WHERE a.handle=? AND a.disabled_at IS NULL LIMIT 1').bind(userHandle).first();if(!record){const blocked=(await Promise.all(keys.map(key=>throttle(db,key,LOGIN_FAILURE_LIMIT)))).some(Boolean);return failure(blocked?429:401,blocked?'Muitas tentativas. Tente novamente mais tarde.':'Identificador ou credencial inválidos.')}const[,version,iterations,salt,expected]=record.verifier.split('$');if(version!=='v1'||iterations!=='600000'){const blocked=(await Promise.all(keys.map(key=>throttle(db,key,LOGIN_FAILURE_LIMIT)))).some(Boolean);return failure(blocked?429:401,blocked?'Muitas tentativas. Tente novamente mais tarde.':'Identificador ou credencial inválidos.')}const decoded=Uint8Array.from(atob(salt.replaceAll('-','+').replaceAll('_','/').padEnd(Math.ceil(salt.length/4)*4,'=')),character=>character.charCodeAt(0));const actual=await deriveCredential(value.password,decoded);if(!constantTimeEqual(actual,record.verifier)||!constantTimeEqual(expected,actual.split('$')[4])){const blocked=(await Promise.all(keys.map(key=>throttle(db,key,LOGIN_FAILURE_LIMIT)))).some(Boolean);return failure(blocked?429:401,blocked?'Muitas tentativas. Tente novamente mais tarde.':'Identificador ou credencial inválidos.')}await Promise.all(keys.map(key=>db.prepare('DELETE FROM login_throttles WHERE handle=?').bind(key).run()));return response({session_token:await createSession(db,record.user_id)})}
async function recover(request,db){const value=await body(request);const userHandle=handle(value.handle);if(typeof value.recovery_code!=='string'||typeof value.new_password!=='string')throw new Error('Recuperação inválida.');const keys=[throttleKey('recover-handle',userHandle),throttleKey('recover-ip',clientAddress(request))];const limit=await rejectIfBlocked(db,keys);if(limit)return limit;const blocked=(await Promise.all(keys.map(key=>throttle(db,key,RECOVERY_ATTEMPT_LIMIT)))).some(Boolean);if(blocked)return failure(429,'Muitas tentativas. Tente novamente mais tarde.');const account=await db.prepare('SELECT user_id FROM accounts WHERE handle=? AND disabled_at IS NULL LIMIT 1').bind(userHandle).first();if(!account)return failure(401,'Recuperação inválida.');const codes=await db.prepare('SELECT code_hash FROM recovery_codes WHERE user_id=? AND used_at IS NULL').bind(account.user_id).all();let selected;for(const item of codes.results||[]){const[,version,iterations,salt]=item.code_hash.split('$');if(version!=='v1'||iterations!=='600000')continue;const decoded=Uint8Array.from(atob(salt.replaceAll('-','+').replaceAll('_','/').padEnd(Math.ceil(salt.length/4)*4,'=')),character=>character.charCodeAt(0));if(constantTimeEqual(await deriveCredential(value.recovery_code,decoded),item.code_hash)){selected=item.code_hash;break}}
  if(!selected)return failure(401,'Recuperação inválida.');const timestamp=now();const consumed=await db.prepare('UPDATE recovery_codes SET used_at=? WHERE user_id=? AND code_hash=? AND used_at IS NULL').bind(timestamp,account.user_id,selected).run();if(Number(consumed.meta?.changes??consumed.changes??0)!==1)return failure(401,'Recuperação inválida.');const salt=new Uint8Array(16);crypto.getRandomValues(salt);const clear=[...keys,throttleKey('login-handle',userHandle),throttleKey('login-ip',clientAddress(request))];await db.batch([db.prepare('UPDATE credential_verifiers SET verifier=?,updated_at=? WHERE user_id=?').bind(await deriveCredential(value.new_password,salt),timestamp,account.user_id),db.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').bind(timestamp,account.user_id),...clear.map(key=>db.prepare('DELETE FROM login_throttles WHERE handle=?').bind(key))]);return response({session_token:await createSession(db,account.user_id)})}

async function syncSnapshot(db,userId){const row=await db.prepare('SELECT revision,state_json FROM progress_snapshots WHERE user_id=? LIMIT 1').bind(userId).first();return row?{revision:Number(row.revision),state:JSON.parse(row.state_json)}:{revision:0,state:emptySyncState()}}
async function syncPull(request,db){const userId=await authenticated(request,db);return response(await syncSnapshot(db,userId))}
async function syncPush(request,db){const userId=await authenticated(request,db);const value=await body(request);if(!Number.isInteger(value.base_revision)||value.base_revision<0||typeof value.device_id!=='string'||!/^[a-z0-9][a-z0-9_-]{7,63}$/i.test(value.device_id))throw new Error('Operação de sincronização inválida.');const snapshot=await syncSnapshot(db,userId);if(value.base_revision>snapshot.revision)return failure(409,'Conflito de sincronização. Atualize o progresso antes de tentar novamente.');const fresh=[];for(const operation of value.operations||[]){const existing=await db.prepare('SELECT operation_id FROM progress_operations WHERE user_id=? AND operation_id=? LIMIT 1').bind(userId,operation?.operation_id).first();if(!existing)fresh.push(operation)}if(!fresh.length)return response({...snapshot,idempotent:true});const merged=applySyncOperations(snapshot.state,fresh);if(merged.conflict)return response({detail:'Conflito de sincronização. Escolha qual evidência manter.',revision:snapshot.revision,state:snapshot.state,conflict:merged.conflict},409);const revision=snapshot.revision+1;const timestamp=now();const statements=fresh.map(operation=>db.prepare('INSERT INTO progress_operations(user_id,operation_id,base_revision,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').bind(userId,operation.operation_id,value.base_revision,operation.type,JSON.stringify(operation.payload),timestamp));statements.push(db.prepare('INSERT INTO progress_snapshots(user_id,revision,state_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET revision=excluded.revision,state_json=excluded.state_json,updated_at=excluded.updated_at').bind(userId,revision,JSON.stringify(merged.state),timestamp));await db.batch(statements);return response({revision,state:merged.state,idempotent:false})}

export default {async fetch(request,env){if(request.method==='OPTIONS')return preflight(request,env);let result;try{if(request.method!=='POST')result=failure(404,'Rota não encontrada.');else{const url=new URL(request.url);if(!env.DB)result=failure(503,'Sincronização não configurada.');else if(url.pathname==='/auth/register')result=await register(request,env.DB);else if(url.pathname==='/auth/login')result=await login(request,env.DB);else if(url.pathname==='/auth/recover')result=await recover(request,env.DB);else if(url.pathname==='/auth/logout'){const userId=await authenticated(request,env.DB);await env.DB.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').bind(now(),userId).run();result=response({signed_out:true})}else if(url.pathname==='/sync/pull')result=await syncPull(request,env.DB);else if(url.pathname==='/sync/push')result=await syncPush(request,env.DB);else result=failure(404,'Rota não encontrada.')}}catch(error){const message=error instanceof Error?error.message:'';if(message==='Autenticação necessária.')result=failure(401,message);else if(['Envie JSON.','Entrada excede o limite.','JSON inválido.','Entrada inválida.','Identificador inválido.','Credencial inválida.','Recuperação inválida.','Operação de sincronização inválida.','Estado de sincronização inválido.','Lote de sincronização inválido.','Operação de sincronização duplicada.'].includes(message))result=failure(422,message);else result=failure(500)}return cors(request,env,result)}}
